version: '3.9'

services:
  backend:
    build:
      context: ./back
    ports:
      - "4000:4000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=Ladivabdd
    depends_on:
      - mysql
    command: npm run dev

  front:
    build:
      context: ./Front
    ports:
      - "5173:5173"
    volumes:
      - ./Front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: Ladivabdd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
